### ISSUE TITLE
Use additionalFruitTypes.lua to register fruittypes

### ISSUE THREAD

**Issue by fdanapfel** [webalizer-gt/choppedStraw15#2]
Would it be possible to use the additionalFruitTypes. lua from the multifruit tutorial from upsidedown (http://www.modhoster.de/mods/tutorialskriptsmaterials_multifruitformaps) to register the additional fruittypes required by this mod?

**Comment by webalizer-gt** [comment]
It does not matter in which file you register the fruittypes, as long as the code is the same and you only do it once.
