### ISSUE TITLE
straw not spreads  

### ISSUE THREAD

**Issue by Tkaag** [webalizer-gt/choppedStraw15#4]
hey there 
i have a problem with chopped straw 
it speads fine when i run normally as you can see

![image](https://cloud.githubusercontent.com/assets/4026751/13786703/1eafce8a-ead9-11e5-9db6-726275fbeabd.png)

but when i have a trailer behind the combine it will not spreads
![image](https://cloud.githubusercontent.com/assets/4026751/13786825/bcaa20d6-ead9-11e5-8a59-fc069aa6e0b9.png)
hope that you will help with this problem

you have a really nise mod 

Thomas

**Comment by webalizer-gt** [comment]
It seems that the trailer has workAreas for some reason. Choppedstraw parses all attached implements and gets the wrong size.
As this is a very rare situation there will be no fix for that.
If you want to fix by yourself you have to make sure, that only implements of type "cutter" are parsed in line 142 (ChoppedStraw.lua). Checking the joint type maybe another solution.
